spring:

  datasource:
    url: jdbc:mysql://localhost:3306/mykeywordnews
    username: root
    password: qkr96#
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop  #create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    com.tutorial: debug

# HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
# Secret 값은 특정 문자열을 Base64 로 인코딩한 값 사용 (아래 명령어를 터미널에 쳐보면 그대로 나옴)
# $ echo 'spring-boot-security-jwt-tutorial-kwanhee-mykeywordnews-project-parkkwanhee-jpa-react' | base64
#  spring-boot-security-jwt-tutorial-jiwoon-spring-boot-security-jwt-tutorial-parkkwanhee-jpa-react
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWt3YW5oZWUtbXlrZXl3b3JkbmV3cy1wcm9qZWN0LXBhcmtrd2FuaGVlLWpwYS1yZWFjdA==
